# Generated by Django 5.0.4 on 2024-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aboutinfo_logo_alter_aboutinfo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypartner',
            name='name',
            field=models.TextField(default='', help_text="Companie's name"),
        ),
    ]
