# Generated by Django 5.0.4 on 2024-04-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderinfo_sale_alter_orderinfo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ['delivery_date']},
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='delivery_data',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='delivery_address',
            field=models.TextField(default='Minsk, ', help_text='Delivery address'),
        ),
    ]
