# Generated by Django 5.0.4 on 2024-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orderinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='img',
            field=models.ImageField(help_text='Employees photo', upload_to='app/static/info'),
        ),
    ]
