# Generated by Django 5.0.4 on 2024-04-21 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employeeinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, help_text='News photo', null=True, upload_to='app/static/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='salecode',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update date & time'),
        ),
    ]
