# Generated by Django 5.0.4 on 2024-04-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_aboutinfo_updated_at_alter_author_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='qa',
            name='date',
        ),
    ]
