# Generated by Django 5.0.4 on 2024-05-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customerreview_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default='Роман', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.bookgenre'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_price',
            field=models.FloatField(help_text="Order's price"),
        ),
    ]
