# Generated by Django 5.0.4 on 2024-09-06 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutinfo_certificate_aboutinfo_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text="Company's logo", null=True, upload_to='app/static/about'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='video',
            field=models.FileField(blank=True, help_text='About video', null=True, upload_to='app/static/about', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='img',
            field=models.ImageField(blank=True, help_text='Employees photo', null=True, upload_to='app/static/info'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, help_text='News photo', null=True, upload_to='app/static/news'),
        ),
    ]
