# Generated by Django 5.0.4 on 2024-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bannersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersettings',
            name='pags',
            field=models.BooleanField(default=True),
        ),
    ]
