# Generated by Django 5.0.4 on 2024-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bannersettings_pags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Phone number', max_length=50, unique=True),
        ),
    ]
